### ISSUE TITLE
Producer messages not received

### ISSUE THREAD

**Issue by timgalebach** [gerritjvv/kafka-fast#15]
I'm running the below code:
```clojure
(def c (create-connector [{:host "localhost" :port 9092}] {}))
(send-msg c "yo" (.getBytes "hi"))
```
The connector gets created without an error, and topic "yo" exists. I am able to start a console consumer listening on that topic and have it print messages sent from a console producer, but the kafka-fast producer's messages aren't received. Am I missing something obvious here?

**Comment by gerritjvv** [comment]
hi, 
please try setting :flush-on-write to true to see the message on write.
for performance messages are buffered and not sent directly by default.

```clojure
(def c (create-connector [{:host "localhost" :port 9092}]  {:flush-on-write true}))
(send-msg c "yo" (.getBytes "hi"))
```

I've updated the doc in https://github.com/gerritjvv/kafka-fast/blob/master/kafka-clj/doc/vagrant.md to reflect this.

**Comment by timgalebach** [comment]
Yup, works perfectly. I might recommend adding the note about :flush-on-write to the main doc as well, because it was very confusing when the 278 long string worked, and then subsequent small tests failed.

Great lib though, looking forward to rolling it into my current project!

**Comment by gerritjvv** [comment]
great!, thanks! I'll update the main docs also.
