### ISSUE TITLE
Issues with vagrant

### ISSUE THREAD

**Issue by BernhardBln** [gerritjvv/kafka-fast#16]
Hey,

wanted to try your vagrant sample, but received this error by vagrant up:

==> services1: Dependency Installed:
==> services1:   compat-readline5.x86_64 0:5.2-17.1.el6  ruby.x86_64 0:1.8.7.374-4.el6_6      
==> services1:   ruby-irb.x86_64 0:1.8.7.374-4.el6_6     ruby-libs.x86_64 0:1.8.7.374-4.el6_6 
==> services1:   ruby-rdoc.x86_64 0:1.8.7.374-4.el6_6   
==> services1: Complete!
==> services1: /vagrant/vagrant/scripts/redis-cluster.sh: line 50: ruby-install: command not found

Any idea? Maybe my vagrant version is too old? (Vagrant 1.6.5) - I also had to remove the config.vbguest.auto_update config from the Vagrantfile, as it didn't know that parameter...

**Comment by gerritjvv** [comment]
try with 1.7.4 see if it works, otherwise I guess the vagrant file needs an update :)

**Comment by BernhardBln** [comment]
Hi, 
I still have both problems with 1.7.4.

This is what vagrant says about the config file:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'vbguest'.
```

Commenting it out still gives me the error message from above ("ruby-install not found").

**Comment by gerritjvv** [comment]
mm.. weird I'll have a look.

**Comment by BernhardBln** [comment]
Thank you :)

**Comment by gerritjvv** [comment]
the vbguest can be fixed by running

vagrant plugin uninstall vagrant-vbguest
vagrant plugin install vagrant-vbguest

**Comment by gerritjvv** [comment]
The ruby-install errors you're seeing is in the kafka-fast/kafka-clj/vagrant/scripts/redis-cluster.sh file 

Basically it tries to download ruby-install and install it, my guess is that something goes wrong with this process. Try to run it manually from the redis box in "services1" i.e vagrant up services1, vagrant ssh services1

I did this locally and didn't see any issues but doesnt help you :).

The commands to run are below.
Ping me with the output if any failure.

```
 wget -O ruby-install-0.5.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.5.0.tar.gz
 tar -xzvf ruby-install-0.5.0.tar.gz
 cd ruby-install-0.5.0/
 sudo make install

 #install ruby gems with older version of ruby
 yum -y install rubygems

 #install latest version of ruby
 ruby-install ruby
```

**Comment by BernhardBln** [comment]
Hi,
didn't know it was a plugin, `vagrant plugin install vagrant-vbguest` helped :)

Same error when doing stuff manually; the reason is: the "sudo make install" installs ruby to `/usr/local/bin/ruby-install`, but when I do `ruby-install`, I get "command not found".

When calling `/usr/local/bin/ruby-install` with the full-qualified path, everything works.

Which doesn't make much sense, if you look at the path...

```[vagrant@services1 ruby-install-0.5.0]$ echo $PATH
/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/vagrant/bin```

More intesting: now **after** I installed ruby with ruby-install, it can actually be called without the full-qualified path:

```[vagrant@services1 ruby-install-0.5.0]$ whereis ruby-install```
```ruby-install: /usr/local/bin/ruby-install```

```[vagrant@services1 ruby-install-0.5.0]$ ruby-install```
```Latest ruby versions:
    ruby:
        1.9.3-p547 [...]```

That doesn't all really make sense to me, but at least I have a workaround now.

Thank you very much for your quick help :)

**Comment by gerritjvv** [comment]
glad I could help :) . I'll add this to a workarounds and troubleshooting page for future reference.
