### ISSUE TITLE
deployment options

### ISSUE THREAD

**Issue by orlin** [gerritjvv/kafka-fast#17]
I just watched [Bobby Calderwood's Conj talk](https://www.youtube.com/watch?v=qDNPQo9UmJA) and started looking into how one could use Kafka.  This library seems to be the best choice for a Clojure backend.  I consider OpenShift to be a great PaaS for Clojure apps deployment (especially for its "free" plan) and I noticed they had [partnered with Mesosphere](https://blog.openshift.com/mesospheres-datacenter-operating-system-and-openshift-an-exciting-partnership/) which offers Kafka.  Guessing that uses Zookeeper though (rather than Redis) which means incompatible?  Since you already have a Vagrant template, maybe Hashicorp's Atlas would be a better fit?  I also found articles online for non-clustered deployment of Kafka, can this library be used in such cases, with ease -- a small project that wants to use the right architecture / workflow, yet may not need to (ever) *"scale"*?

**Comment by gerritjvv** [comment]
This library uses redis but doesn't mean that the kafka broker needs to use it. i.e you can deploy on any framework as long as you have access to a redis installation you can use this kafka client. 
I've not tried redis on openshift but have a look at this link https://blog.openshift.com/enabling-redis-for-your-app/
