### ISSUE TITLE
Vagrantbox not working anymore

### ISSUE THREAD

**Issue by nblumoe** [gerritjvv/kafka-fast#30]
Trying to run `vagrant up` results in the following error message:

```
$ vagrant up
Bringing machine 'zookeeper1' up with 'virtualbox' provider...
Bringing machine 'broker1' up with 'virtualbox' provider...
Bringing machine 'broker2' up with 'virtualbox' provider...
Bringing machine 'broker3' up with 'virtualbox' provider...
Bringing machine 'services1' up with 'virtualbox' provider...
==> zookeeper1: Box 'gerritjvv/centos-6.5-java' could not be found. Attempting to find and install...
    zookeeper1: Box Provider: virtualbox
    zookeeper1: Box Version: >= 0
==> zookeeper1: Loading metadata for box 'gerritjvv/centos-6.5-java'
    zookeeper1: URL: https://atlas.hashicorp.com/gerritjvv/centos-6.5-java
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: gerritjvv/centos-6.5-java
Address: https://atlas.hashicorp.com/gerritjvv/centos-6.5-java
Requested provider: [:virtualbox]
```

Looking at https://atlas.hashicorp.com/gerritjvv/boxes/centos-6.5-java the box was revoked and does not have any supported providers. Was this done on purpose?

If the Vagrant setup is not maintained and supported anymore, it probably should be removed from the documentation, too.

Thanks & cheers

**Comment by gerritjvv** [comment]
Hi, this is my fault, sorry, I'll have a new box up and running soon.

**Comment by nblumoe** [comment]
No worries, happy to hear that you are planning to bring it up again.

**Comment by gerritjvv** [comment]
this should be working now, just merged https://github.com/gerritjvv/kafka-fast/pull/31,
please try again, I've also updated the vagrant doc.

**Comment by nblumoe** [comment]
thanks @gerritjvv 

But actually I think this is not working. you might need to specify a box that is available from Hashicorp Atlas ideally, like `hashicorp/precise64`  or `ubuntu/precise64`. If the current Vagrantfile works for you, it might be because you have a local box named `precise`?!

Here is the related error message I see:
```
==> zookeeper1: Adding box 'precise64' (v0) for provider: virtualbox
    zookeeper1: Downloading: precise64
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/nblu/src/experiments/gatoka/precise64
```

**Comment by gerritjvv** [comment]
true I had it set to just precise64 :(, just updated to hashicorp/precise64, please try again see if it works for you.

**Comment by nblumoe** [comment]
Working now, thanks again! 👍

**Comment by gerritjvv** [comment]
noprobs, thanks for reporting it! :)
