### ISSUE TITLE
Buffered-msgs! unique with differents topic in Listeners

### ISSUE THREAD

**Issue by AlejandroArmenteros** [gerritjvv/kafka-fast#42]
Hi all.

first thanks for share kafka-fast with the community. it's a really good job!

But i want to ask about an error adding a listener in service. I did it with a method that i found in your code ( kafka-clj.consumer.node/buffered-msgs )

i wrote this code to set-listeners

```
(defn set-listeners
  [connector topic coll-func decoder & [n timeout-ms]]
  (let [node (create-node! connector [topic])
        buffer (buffered-msgs node
                              (if n n 1000)
                              (if timeout-ms timeout-ms 3000))]
    (go-loop [] (doseq [msg (seq (<! buffer))]
                  (let [content (decoder (:bts msg))]
                    (doall (map #(% content) coll-func))))
                (recur))))
```

where coll-func is a sequence of functions to execute with the received data via kafka.

When i send only message to 1 topic, everything works well. But when i have two listeners with differents topic, the message goes to wrong channel.

I don't know how to do that, but i think my next step will be run create-node! only 1 time, and save with an atom one map defined like: 

```

{ 
  :topic1 '(listeners-to-topic1) 
  :topic2 '(listeners-to-topic2)  
  .....
}
```

i appreciate if you can suggest me some options or if i'm doing something wrong.

Best Regards!

**Comment by gerritjvv** [comment]
hi, 
thanks for the kind words :).

The issue you're describing seems like I bug if you only create a single node per topic there should be no shared state that would allow one message to go to another, I'll have a closer look during the week at it.

Ideally you would only create node once and then add remove topics from it. A node starts up lots of background resources and kafka fetcher threads that are meant to be used with multiple topics etc.  

I would suggest you change the design to having a single context map that you pass around that contains

```
(def ctx {:node node :listeners (atom {})})


(defn add-listener! 
    [ctx topic listener]
   {:pre [(:listeners ctx) topic (fn? listener)]}
    (update ctx :listeners swap! update topic #(conj (set %) listener)))

;;;to add alistener
(defn remove-listener! 
   [ctx topic listener] 
   {:pre [(:listeners ctx) topic (fn? listener)]}
   (update ctx :listeners swap! update topic #(remove (partial = listener) %)))

(defn notify-listeners
   [ctx topic msg] 
  (when (:listeners ctx) (doseq [l (get @(:listeners ctx) topic)] (l msg))))
```

some improvements could be adding a check to make sure that the node contains the topic that is being listened for and if not add that topic.

**Comment by AlejandroArmenteros** [comment]
It works for me!!.

Additionally, i added another layer for parse the received message in each topic.

Thanks for your help!!

**Comment by gerritjvv** [comment]
great to hear!!!.

**Comment by gerritjvv** [comment]
just to followup on this, it turns out not to be a bug. 

Each connector has a series of shared resources in redis, which are prefixed with the :redis-conf :group-name, meaning if you create two connectors with the same group-name but different topics you will get topics from the whole group.
