### ISSUE TITLE
Parent folder does not exist: \tmp\kafka-retry-cache

### ISSUE THREAD

**Issue by xingzhefeng** [gerritjvv/kafka-fast#43]
windows 7  exception  when  kafka-clj.client/create-connector

```
CompilerException java.io.IOError: java.io.IOException:
 Parent folder does not exist: \tmp\kafka-retry-cache,
 compiling:(kafkaproducer.clj:9:8) 
```

**Comment by xingzhefeng** [comment]
(def c (create-connector [{:host "api.baidu.com" :port 9090}] {:flush-on-write true :retry-cache-file (clojure.java.io/file (str (System/getProperty "java.io.tmpdir") (System/nanoTime)))}))


now is ok

**Comment by gerritjvv** [comment]
great catch, its been years since I worked with windows and sort off just accept /tmp/ exists :)

could you make a PR for this? 

thanks!

**Comment by gerritjvv** [comment]
fixed in https://github.com/gerritjvv/kafka-fast/pull/44
