### ISSUE TITLE
Outdated documentation section for single producer

### ISSUE THREAD

**Issue by vlebedev** [gerritjvv/kafka-fast#5]
The example from 'Single producer' section of the documentation won't work. The problem is that the signature of `send-messages` function has been changed, now this function takes four parameters, not three. These parameters are not well documented in the code, so experimentally I found that instead of `(send-messages p {} d)` I have to use `(send-message p p {} d)`. Which is a little bit weird, IMHO.

**Comment by gerritjvv** [comment]
Hi, the first two parameters are : connector and single producer.
I'll create a multi arity version of this function so that the documentation is accurate again, 
thanks for spotting this!!

**Comment by gerritjvv** [comment]
the main reason for this extra argument was for a new way of handling ack > 0, by using MapDB as a send cache, this is created per connector. 

I'm going to create a global send cache that can be used in the case of single producer sends and also document the usage of both arities.

**Comment by vlebedev** [comment]
Great, many thanks for the library!

**Comment by gerritjvv** [comment]
fixed with the latest update to master.

**Comment by gerritjvv** [comment]
@vlebedev  noprobs, if you find any more issues don't hesitate to create a ticket (if I don't respond ping me on my email, sometimes the git notifications don't get through to my mail ;).
