### ISSUE TITLE
Min offset assumption is wrong on large kafka backlog

### ISSUE THREAD

**Issue by Igor-Vlasov** [gerritjvv/kafka-fast#58]
Client tries to calculate min max offset for future work and sanity checks in getting saved offset, based on ListOffsets API call, but returned set of offsets is reduced to 500 by default:
https://github.com/gerritjvv/kafka-fast/blob/fd149d8744c8100b2a8f4d09f1a251812e7baf6a/kafka-clj/src/kafka_clj/consumer/util.clj#L18

Default setting:
https://github.com/gerritjvv/kafka-fast/blob/master/kafka-clj/src/kafka_clj/fetch.clj#L105

It is used to check starting offset here:
https://github.com/gerritjvv/kafka-fast/blob/master/kafka-clj/src/kafka_clj/consumer/work_organiser.clj#L192

And client gives wrong assumption about earliest available offset here:
https://github.com/gerritjvv/kafka-fast/blob/master/kafka-clj/src/kafka_clj/consumer/work_organiser.clj#L178

Without tweaking of this parameter client will not get data earlier than 500 offsets, other data will be discarded, and with retention policy in kafka, there is a possibility of data loss. A separate call is needed to get minimal possible offset in kafka.

**Comment by gerritjvv** [comment]
Hi @Igor-Vlasov , thanks for catching this. I'm on holidays atm. I'll be able to look at this around the 13th. If you have a PR I can review and merge that in sooner if you'd like.

**Comment by Igor-Vlasov** [comment]
No problem, we currently worked around this by setting :max-offsets to high value in configuration. I think I will not be able to issue PR soon, we currently have a lot of post data center migration work. This bug caused us some painful issues during migration, so I have decided to share it with you.
