### ISSUE TITLE
something wrong in java folder part

### ISSUE THREAD

**Issue by luckyandy** [gerritjvv/kafka-fast#8]
![image](https://cloud.githubusercontent.com/assets/12490881/8276049/ce20fb28-18e3-11e5-8965-d80f76d70e27.png)

I just test it in java, without the clojure. Would you please tell me how to fix it?

**Comment by gerritjvv** [comment]
Hi, can you elaborate a bit more about the issue? 
I'm opening the BrokerConf.java and Producer.java classes and they appear fine  (using intelij with the https://cursiveclojure.com/ plugin) . If its your IDE complaining you'll need to make sure it has support for leiningen, or generate the pom.xml file from lein and then import the project as a maven project which should resolve the dependencies.

**Comment by gerritjvv** [comment]
closing this for now. If the problems still persist please reopen this ticket. Thanks
